### ISSUE TITLE
Missing software license information

### ISSUE THREAD

**Issue by h3xx** [jeremysalwen/TalentedHack#4]
According to [the old site on Google Code](https://code.google.com/archive/p/talentledhack/), this software is GPL 3.0 licensed. However this license is missing from this repo.

**Comment by fpesari** [comment]
I agree but even if the licensing info is missing, due to the fact that it's the GPLv3, the code is automatically released under the GPLv3.

**Comment by h3xx** [comment]
I'm only peripherally aware that the code is released under GPL v3. The point of #5 is to explicitly declare the license.

I'm not sure what you mean about being "automatically released" under GPLv3.

This issue and #5 just needs author intervention to clear up the license ambiguity.

**Comment by fpesari** [comment]
The GPLv3 works like this: even if a license notice is missing, users should be able to ask the author a copy of the license and receive it.

AFAIK, it's impossible to release code based on other GPLv3 code that is not under the GPLv3. This means that this code is already under the GPLv3, but #5 is right, it's better to have a license notice.

**Comment by jeremysalwen** [comment]
Sorry, on Google Code there was a separate field for the license, which didn't get copied over when moving to Github.  PR including GPL3 license merged.
